'use client';
import { useEffect } from "react";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap.bundle.min.js');
  }, []);

  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
